# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='monto',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
